apiVersion: v1
kind: ConfigMap
metadata:
  name: themer-config
data:
  # property-like keys; each key maps to a simple value
  APP_COLOR: red
  APP_MODE: prod

  #file-like keys  --env file
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
    
