apiVersion: v1
kind: Pod
metadata:
  name: uploader-layout-pod
spec:
  containers:
    - name: uploader-layout-containers
      image: nginx
      ports:
        - containerPort: 8080
      env:
        - name: BOOTSTRAP_URI
          valueFrom:
            configMapKeyRef:
              name: app-frontend-config
              key: APP
