apiVersion: v1
kind: ReplicationController
metadata:
    name: myapp-rc
    labels:
        type: frontend
        app: myapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: frontend
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3

