apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    type: frontend
    app: myapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: frontend
        app: myapp
        env: production
    spec:
      containers: 
        - name: redis
          image: redis
  replicas: 8
  selector:
    matchLabels:
      env: production
