apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    env: staging
spec:
  containers:
    - name: myapp-pod-containers
      image: nginx
      env:
        - name: USER_NAME
          value: Sharkas
        - name: JOB
          value: Developer
        - name: BDATE
          value: 23May2022
