apiVersion: v1
kind: Pod
metadata:
  name: guiapp-pod
  labels:
    type: backend
    app: guiapp
spec:
  containers:
    - name: myapp-container
      image: redis
  tolerations:  #tolerations is for pod
    - key: "app"
      operator: "Equal"
      value: "backend"
      effect: "NoSchedule"
    - key: "department"
      operator: "Exists"
      effect: "PreferNoSchedule"
