apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: portal-pod
  name: portal-pod
spec:
  containers:
  - image: hello-world
    name: portal-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: env
              operator: NotIn
              values: 
                - testing
                - production
status: {}
